### ISSUE TITLE
Docker - Apps testing - Create docker image

### ISSUE THREAD

**Issue by GlennRicaud** [enonic-archive/docker-xp6#4]
* Create docker image to run xp-apps UI testing

**Comment by jsi** [comment]
Take a look at this: https://hub.docker.com/r/sivesind/chrome-node-js/~/dockerfile/

I think it is fairly close.

**Comment by drerik** [comment]
@GlennRicaud @jsi I think this is a unique container and not something that should be added to this xp container. agree?

**Comment by jsi** [comment]
This was completed back in 2017 by this image which currently is hosted on my private user.  Not sure if this is the best solution, but it works for now: https://hub.docker.com/r/sivesind/chrome-node-js/
